// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmZNUocYmDzmTihe2eu9XUYEECUZgq5M',
    appId: '1:1053126543711:web:128870eb50b34d25728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    authDomain: 'hunger-cbd8e.firebaseapp.com',
    databaseURL: 'https://hunger-cbd8e-default-rtdb.firebaseio.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
    measurementId: 'G-RETKSH07HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sr0PbsNU4ZbtULPHz6hU9YMINAq2src',
    appId: '1:1053126543711:android:8410c011c71402ae728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    databaseURL: 'https://hunger-cbd8e-default-rtdb.firebaseio.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpUB55QMjXwDYklTrjAz6eDH0PHLM0KQ',
    appId: '1:1053126543711:ios:9ecf4617662b5ad1728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    databaseURL: 'https://hunger-cbd8e-default-rtdb.firebaseio.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
    androidClientId: '1053126543711-d1r2258ojhs6c7sfljqpjbicvglplkvj.apps.googleusercontent.com',
    iosClientId: '1053126543711-r9lq3osr0ep0c0chb6hgm7isro8eki3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpUB55QMjXwDYklTrjAz6eDH0PHLM0KQ',
    appId: '1:1053126543711:ios:9ecf4617662b5ad1728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    databaseURL: 'https://hunger-cbd8e-default-rtdb.firebaseio.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
    androidClientId: '1053126543711-d1r2258ojhs6c7sfljqpjbicvglplkvj.apps.googleusercontent.com',
    iosClientId: '1053126543711-r9lq3osr0ep0c0chb6hgm7isro8eki3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmZNUocYmDzmTihe2eu9XUYEECUZgq5M',
    appId: '1:1053126543711:web:abfdee05ea1dd2c6728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    authDomain: 'hunger-cbd8e.firebaseapp.com',
    databaseURL: 'https://hunger-cbd8e-default-rtdb.firebaseio.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
    measurementId: 'G-SVEK2P8VNG',
  );
}
